name: Get Pac

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone powerplatform-actions
        run: |
          git clone https://github.com/microsoft/powerplatform-actions.git powerplatform-actions
          git checkout 7bbd803800dd4d35eb8d8aa5b132404d25df043d

      - uses: actions/upload-artifact@v2
        with:
          name: pac
          path: powerplatform-actions/dist/pac/tools